server:
  port: 8080
  servlet:
    encoding:
      charset: utf-8
      force: true

spring:
  datasource:
    url: jdbc:mysql://mindbridge.c5hgfzyunggm.ap-northeast-2.rds.amazonaws.com:3306/mindbridge?useSSL=false&setTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      default_batch_fetch_size: 100
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 100MB
cloud:
  aws:
    credentials:
      accessKey: ${S3_ACCESS_KEY}
      secretKey: ${S3_SECRET_KEY}
    s3:
      bucket:
    region:
      static: ap-northeast-2
    stack:
      auto: false
logging:
  level:
    '[kr.co.moneybridge]': INFO