server:
  port: 8080
  servlet:
    encoding:
      charset: utf-8
      force: true

spring:
  datasource:
    url: jdbc:mysql://team-d.cajd2qdktvcd.ap-northeast-2.rds.amazonaws.com:3306/team-d?useSSL=false&&allowPublicKeyRetrieval=true&setTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      default_batch_fetch_size: 100
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 100MB

  config:
    activate:
      on-profile: prod
cloud:
  aws:
    credentials:
      accessKey: ${S3_ACCESS_KEY}
      secretKey: ${S3_SECRET_KEY}
    s3:
      bucket:
    region:
      static: ap-northeast-2
    stack:
      auto: false
logging:
  level:
    '[kr.co.moneybridge]': INFO



chatgpt:
  key: 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